- name: Create user 
  become: true
  ansible.builtin.user:
    name: "{{ username }}"
    shell: /bin/zsh
    groups: sudo,docker
    append: yes
    password: ''

- name: Make sudo without password for user
  become: true
  ansible.builtin.copy:
    dest: /etc/sudoers.d/80-{{ username }}-sudo-user
    content: "{{ username }} ALL=(ALL) NOPASSWD:ALL"
    mode: 0440
    validate: 'visudo -cf %s'
